### ISSUE TITLE
Errors with npm install

### ISSUE THREAD

**Issue by jochenonline** [Excelian/Angular-Material-ECMA6-Dashboard#1]
Whenn processing `npm install` I get the following errors. Do you have any hint, what is the reason and how I can solve it?

(This might be the reason: https://github.com/brianmcd/contextify/issues/149)

```
$ npm install
npm WARN package.json Dependency 'karma-firefox-launcher' exists in both dependencies and devDependencies, using 'karma-firefox-launcher@^0.1.3' from dependencies
npm WARN package.json Dependency 'karma' exists in both dependencies and devDependencies, using 'karma@https://registry.npmjs.org/karma/-/karma-0.12.28.tgz' from dependencies
npm WARN package.json systemjs-builder@0.4.5 No repository field.

> contextify@0.1.9 install /home/jochen/git/Angular-Material-ECMA6-Dashboard/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/jochen/git/Angular-Material-ECMA6-Dashboard/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In destructor ‘virtual ContextifyContext::~ContextifyContext()’:
../src/contextify.cc:34:9: error: ‘ContextDisposedNotification’ is not a member of ‘v8::V8’
         v8::V8::ContextDisposedNotification();
         ^
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory `/home/jochen/git/Angular-Material-ECMA6-Dashboard/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-51-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jochen/git/Angular-Material-ECMA6-Dashboard/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jochen/git/Angular-Material-ECMA6-Dashboard/npm-debug.log
```

**Comment by mickeyvip** [comment]
Seem to work for node `v0.10.x`.

Installed without errors on node `0.10.38`, npm `1.4.28`.

``` bash
$ npm install    
npm WARN package.json systemjs-builder@0.4.5 No repository field.

> contextify@0.1.9 install /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
  SOLINK_MODULE(target) Release/contextify.node: Finished
assetgraph@1.13.1 node_modules/assetgraph
├── cssmin@0.3.1
├── passerror@1.0.1
├── setimmediate@1.0.2
├── createerror@0.4.1
├── deep-extend@0.2.11
├── imageinfo@1.0.4
├── uglifyast@0.3.1
├── normalizeurl@0.1.3
├── mkdirp@0.3.5
├── async@0.2.9
├── xmldom@0.1.19
├── cssom-papandreou@0.2.4-patch6
├── request@2.9.153
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── source-map@0.1.33 (amdefine@0.1.0)
├── httperrors@0.2.0 (createerror@0.0.1)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@4.2.1 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@1.0.0)
├── seq@0.3.5 (chainsaw@0.0.9, hashish@0.0.4)
├── urltools@0.2.0 (underscore@1.5.2, glob@3.2.11)
├── uglify-js-papandreou@2.4.13-patch1 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.40)
├── minimize@0.7.6 (utile@0.2.1, htmlparser2@3.7.3)
├── html-minifier@0.6.8 (relateurl@0.2.5, change-case@2.1.5, clean-css@2.2.20, cli@0.6.5, uglify-js@2.4.15)
├── accord@0.11.0 (fobject@0.0.0, resolve@0.7.4, when@3.6.3, indx@0.1.2, uglify-js@2.4.15)
└── jsdom@0.11.0 (xmlhttprequest@1.6.0, cssom@0.3.0, nwmatcher@1.3.3, cssstyle@0.2.22, htmlparser2@3.8.2, contextify@0.1.9)
```

**Comment by jochenonline** [comment]
I am using node `0.12.x`. Do I have to downgrade? That would be a pitty.

**Comment by hughest** [comment]
Hi,

It is working ok on v0.12.2 here, maybe try that.

**Comment by TusharaFernando** [comment]
Currently travis is building on 0.10 I'll look to upgrade it on Thursday to run on both.

**Comment by jochenonline** [comment]
@hughest : I am working with `0.12.2`. So what could be wrong else?

**Comment by mickeyvip** [comment]
Actually clean installing with node `v0.10.38` produces many errors.

And after giving execution permission to a bunch of files, the project runs, but it is not functional on client side - many files are missing:

``` bash
$ ./script/start 
[Error: Failed to find ../../app-compiled/components/dashboard/alerts/alerts.css from /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/main.css in [
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard/settings,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/shared,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/side-menu,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/top-bar,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/angular-material,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/normalize-css,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets
]]
Error: Failed to find ../../app-compiled/components/dashboard/alerts/alerts.css from /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/main.css in [
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard/settings,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/shared,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/side-menu,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/top-bar,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/angular-material,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/normalize-css,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets
]
    at exists (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:87:15)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:137:23
    at Array.forEach (native)
    at run (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:122:11)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:167:9
    at Rework.use (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework/index.js:50:3)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/script/lib/css.js:27:8
    at Gatherer.<anonymous> (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/read-file-stdin/node_modules/gather-stream/index.js:41:5)
    at Gatherer.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
@import 'variables.css';

@import '../../components/normalize-css/normalize.css';
@import "../../components/angular-material/angular-material.css";
@import "../../app/components/top-bar/top-bar.css";
@import"../../app/components/side-menu/side-menu.css";
@import"../../app/components/dashboard/dashboard.css";
@import 'shared/base.css';
@import"../../app/components/dashboard/settings/user-settings.css";
@import"../../app-compiled/components/dashboard/alerts/alerts.css";

Started web server on http://localhost:3010
{ verbose: false,
  root: './client',
  glob: [ '**/*' ],
  host: 'localhost',
  port: 8888 }
Watching files!
GET /variables.css 404 26 - 7.772 ms
GET /shared/base.css 404 28 - 1.371 ms
GET /app-compiled/components/dashboard/alerts/alerts.css 404 64 - 1.109 ms
GET /components/plugin-text/text.js 404 43 - 0.237 ms
GET /components/plugin-text/text.js 404 43 - 0.157 ms
```

**Comment by hughest** [comment]
Ok - thanks for the info.  We will take a look and get it resolved.

**Comment by TusharaFernando** [comment]
It turns out that the issue was related to this error https://github.com/assetgraph/assetgraph-builder/issues/162 I have removed assetgraph as a dependency until this is fixed. Travis is now building on 0.12 also
