### ISSUE TITLE
alerts.css missing 

### ISSUE THREAD

**Issue by mickeyvip** [Excelian/Angular-Material-ECMA6-Dashboard#2]
First - needed to switch to node `v0.10.38` for `npm install` to install run without errors, but I still got errors for `assetgraph-builder` package.

Then needed to add execution permission to each file in `script` folder.

Then needed to add execution permission to `script/lib/css.js` file.

Then I got this:

``` bash
$ ./script/start              
[Error: Failed to find ../../app-compiled/components/dashboard/alerts/alerts.css from /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/main.css in [
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard/settings,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/shared,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/side-menu,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/top-bar,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/angular-material,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/normalize-css,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets
]]
Error: Failed to find ../../app-compiled/components/dashboard/alerts/alerts.css from /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/main.css in [
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard/settings,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets/shared,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/dashboard,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/side-menu,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/app/components/top-bar,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/angular-material,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/components/normalize-css,
    /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/client/assets/stylesheets
]
    at exists (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:87:15)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:137:23
    at Array.forEach (native)
    at run (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:122:11)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework-import/index.js:167:9
    at Rework.use (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/rework/index.js:50:3)
    at /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/script/lib/css.js:27:8
    at Gatherer.<anonymous> (/Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/read-file-stdin/node_modules/gather-stream/index.js:41:5)
    at Gatherer.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
@import 'variables.css';

@import '../../components/normalize-css/normalize.css';
@import "../../components/angular-material/angular-material.css";
@import "../../app/components/top-bar/top-bar.css";
@import"../../app/components/side-menu/side-menu.css";
@import"../../app/components/dashboard/dashboard.css";
@import 'shared/base.css';
@import"../../app/components/dashboard/settings/user-settings.css";
@import"../../app-compiled/components/dashboard/alerts/alerts.css";

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/fb-flo/node_modules/websocket/build/Release/bufferutil.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/mickeyvip/dev/nodejs/Angular-Material-ECMA6-Dashboard/node_modules/fb-flo/node_modules/websocket/build/Release/bufferutil.node
  Expected in: dynamic lookup

Started web server on http://localhost:3010
GET /variables.css 404 26 - 2.066 ms
GET /shared/base.css 404 28 - 0.592 ms
GET /app-compiled/components/dashboard/alerts/alerts.css 404 64 - 0.151 ms
GET /favicon.ico 404 24 - 0.171 ms
GET /components/plugin-text/text.js 404 43 - 0.136 ms
GET /components/plugin-text/text.js 404 43 - 0.124 ms
GET /variables.css 404 26 - 0.260 ms
GET /shared/base.css 404 28 - 0.791 ms
GET /app-compiled/components/dashboard/alerts/alerts.css 404 64 - 0.138 ms
GET /variables.css 404 26 - 0.354 ms
GET /shared/base.css 404 28 - 0.502 ms
GET /app-compiled/components/dashboard/alerts/alerts.css 404 64 - 0.154 ms
GET /components/plugin-text/text.js 404 43 - 0.190 ms
GET /components/plugin-text/text.js 404 43 - 0.104 ms
^C./script/start: line 12: 81348 Trace/BPT trap: 5       node ./script/lib/watch.js --root ./client
```

**Comment by fabdrol** [comment]
Same problem here...

**Comment by crissdev** [comment]
@mickeyvip Thanks for tips to make this app runnable. I tried with node 0.12 and still got the same error.

@TusharaFernando Consider adding notes about making the aformentioned files executable in [README.md](https://github.com/Excelian/Angular-Material-ECMA6-Dashboard#running-the-application).

**Comment by TusharaFernando** [comment]
Allerts.css is removed from main. Added the notes as @crissdev suggested
